HANGHAE404/B2BSaas-FE

- src/page/Signup.tsx
feat: signup page axios-post 추가
> feat: signup page axios-post 추가

- src/page/Login.tsx
- src/page/Signup.tsx
.env 파일 추가
signup axios call 시도, 회원가입 버튼 오작동 수정 중
링크 추가(회원가입 페이지, 로그인 페이지)
> feat: signup page

- src/page/Login.tsx
- src/page/Signup.tsx
feat: 발송용 이메일 칸 추가
fix: async await 구문, 서버 측 request 관련 수정.
서버측 200, 304 코드
> feat: 발송용 이메일 칸 추가 fix: async await 구문, 서버 측 request 관련 수정. 서버측 200, 304 코드

- src/page/Signup.tsx
feat: 회원가입 버튼 타입 변경(submit->onclick)
> feat: 회원가입 버튼 타입 변경(submit->onclick)

- src/page/Signup.tsx
> feat: email provider box 추가

- package.json
- src/page/Login.tsx
- src/page/Signup.tsx
- yarn.lock
feat: 이메일 중복확인 기능 추가, login페이지 axios 연동중
> feat: 이메일 중복확인 기능 추가, login페이지 axios 연동중

- src/page/Signup.tsx
> feat: '역할'탭 추가(관리자:0, 일반:1)

- src/components/ClientHeader.tsx
- src/components/modal/AlertModal.tsx
- src/page/ClientRegistration.tsx
- src/page/GroupManageList.tsx
- src/page/SingleUserCreate.tsx
- src/page/TopNav.tsx
- src/page/UploadPage.tsx
- src/shared/Router.tsx
> feat : 고객관리 컴포넌트 생성 + alert은 모달로 교체

- package.json
- src/page/Login.tsx
- src/page/Signup.tsx
- yarn.lock
Feat: 영현님 자료 풀 후 커밋, signup 페이지 회사 이메일 연동된 것 분리
> Feat: 영현님 자료 풀 후 커밋, signup 페이지 회사 이메일 연동된 것 분리

- src/axios/api.ts
- src/page/Login.tsx
- src/util/cookie/index.ts
Feat: login 성공, api.ts 수정(instance, postlogin 추가)
늦어져서 죄송합니다
> Feat: login 성공, api.ts 수정(instance, postlogin 추가)

- src/axios/api.ts
- src/page/Login.tsx
- src/page/Signup.tsx
feat: 
login 쿠키 확인.
signup: 회원가입 완료 후 navigate 추가.
api.ts: headers getcookie 추가.
> feat: login 쿠키 확인/signup: 회원가입 완료 후 navigate 추가/api.ts: headers getcookie 추가.

- src/page/GroupManageList.tsx
1. 조건 상태변화 확인 위해 37,68라인 콘솔 추가
2. isClientState의 true/false 에 따라 전체고객리스트 useList와 그룹 내 클라이언트 데이터리스트는 groupClient 로 분기 처리
= 전체 클라이언트 리스트 호출시 true, 그룹 내 클라이언트 호출시 false 상태로 호출진행
3. 페이지네이션은 에러 수정 필요
> 그룹관리 페이지 기능 구현 중간 커밋

- src/page/Signup.tsx
> fix: selectbox 간 연동 오작동 수정

- src/page/SingleUserCreate.tsx
1. 에러 table 형식 하에는 form 양식이 적절하지 않아서 table 제거 후 form 양식 하에 div 타입으로 입력폼 수정
> feat : 클라이언트 생성 api 수정

- src/page/TopNav.tsx
> feat: logout confirm 추가

- src/page/Login.tsx
- src/page/Signup.tsx
style: login/signup css
*signup 중복확인 빈 칸에도 사용 가능으로 나옴. 수정중
> style: login/signup css

- src/page/Login.tsx
- src/page/Signup.tsx
> style: signup/login css 변경

- src/page/Login.tsx
- src/page/Signup.tsx
style: css 변경 *중복확인 버튼, selectbox 주석처리. 추후 재활용 예정
> style: css 변경 *중복확인 버튼, selectbox 주석처리. 추후 재활용 예정

- src/page/Login.tsx
- src/page/Signup.tsx
> style: css변경(로그인/회원가입)

- src/page/Login.tsx
- src/page/Signup.tsx
- src/page/TopNav.tsx
feat: topnav login 삼항연산자 추가. style: 버튼 및 글씨 색 변경
> feat: topnav login 삼항연산자 추가. style: 버튼 및 글씨 색 변경

- src/page/ClientRegistration.tsx
- src/page/GroupManageList.tsx
- src/page/SingleUserCreate.tsx
- src/page/TopNav.tsx
- src/shared/Router.tsx
그룹관리 header margin 제거, 라우터에 안쓰는 경로 제거, 슬라이드바 주석처리, 고객등록 컴포넌트 경로 수정
> style : 전반적인 CSS 작업

- src/page/GroupManageList.tsx
> feat. fix : 검색기능 관련 에러 수정

- src/axios/api.ts
- src/components/modal/UserInGroupCreateModal.tsx
- src/page/GroupManageList.tsx
그룹관리 내 버튼 토글 수정, 체크박스 체크유무 개선,
> feat : QA 반영 코드 개선, 그룹 내 고객등록 API 테스트 전까지 코드 추가
